version: '3.4'

services:
  Hackwomen-Team-3-Back:
    image: Hackwomen-Team-3-Back
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --Listen 0.0.0.0:5678 api/manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000  
      - 5678:5678