# Generated by Django 4.0.3 on 2023-04-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='adress_city',
            new_name='address_city',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='adress_zipcode',
            new_name='address_zipcode',
        ),
    ]
